name: plant_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.3
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  dio: ^4.0.6
  top_snackbar_flutter: ^2.1.1
  conditional_builder_null_safety: ^0.0.6
  shared_preferences: ^2.0.15
  firebase_auth: ^3.6.4
  google_sign_in: ^5.4.1
  qr_code_scanner: ^1.0.1
  image_picker: ^0.8.5+3
  flutter_login_facebook:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash icon.png
    - assets/images/plant1.svg
    - assets/images/Google.svg
    - assets/images/Facebook.svg
    - assets/images/Bell.svg
    - assets/images/Cart.svg
    - assets/images/user.svg
    - assets/images/leave.svg
    - assets/images/qr-code-scan.svg
    - assets/images/home.svg
    - assets/images/Search.svg
    - assets/images/minus.svg
    - assets/images/plus.svg
    - assets/images/more.svg
    - assets/images/arrow_back.svg
    - assets/images/plant3.png
    - assets/images/stars.svg
    - assets/images/change.svg
    - assets/images/arrow_front.svg
    - assets/images/sun.png
    - assets/images/water.png
    - assets/images/thermometer.png
    - assets/images/globe.png
    - assets/images/arrow_back_black.svg
    - assets/images/like.svg

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
